/* automatically generated by rust-bindgen 0.72.1 */

unsafe extern "C" {
    #[doc = " Simple test library"]
    pub fn add(a: ::core::ffi::c_int, b: ::core::ffi::c_int) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn multiply(x: f64, y: f64) -> f64;
}
unsafe extern "C" {
    pub fn print_hello();
}
