//! Safe Rust wrapper for simple
//!
//! This module was automatically generated by bindings-generat.
//! It provides safe, idiomatic Rust wrappers around the raw FFI bindings.

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

// Note: FFI bindings should be in src/ffi.rs
// Run bindgen on your headers and place the output there
#[path = "ffi.rs"]
mod ffi;

/// Error type for this library
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    /// Null pointer returned
    NullPointer,
    /// FFI function returned an error status
    FfiError(i32),
    /// Unknown error
    Unknown,
}

impl From<i32> for Error {
    fn from(code: i32) -> Self {
        if code == 0 {
            // Success code should not become an error
            Error::Unknown
        } else {
            Error::FfiError(code)
        }
    }
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::NullPointer => write!(f, "Null pointer returned"),
            Error::FfiError(code) => write!(f, "FFI error: {}", code),
            Error::Unknown => write!(f, "Unknown error"),
        }
    }
}

impl std::error::Error for Error {}
